### ISSUE TITLE
White on white text on stats page.

### ISSUE THREAD

**Issue by Jeklah** [Vagelis-Prokopiou/unsaferust.org#1] opened 2022-05-09 10:21 UTC
As pointed out by redditors, white text on white background is being rendered on stats page.
This issue was not noticed due to dark-mode enabled in browser making the text readable.

On the default theme it is white on white, thus unreadable.

**Comment by Vagelis-Prokopiou** [comment] 2022-05-09 11:09
Thanx @Jeklah. I reproduced it myself too.
Let's see what the solution is :-)

**Comment by Jeklah** [comment] 2022-05-09 12:32
Excellent :)
I've found plugins to be the cause of bugs quite often!

**Comment by Vagelis-Prokopiou** [comment] 2022-05-09 12:39
@Jeklah, PR #2  provided some fixes.
Can you verify that the issue is fixed?
The table headers are still problematic for the "Project details" pages, but we have some progress.

**Comment by Jeklah** [comment] 2022-05-09 12:44
I can indeed verify this fix works! The text on home page and stats is now
black and very readable :)

**Comment by Jeklah** [comment] 2022-05-09 12:45
And the table headers look good, nice and bold :)

**Comment by Vagelis-Prokopiou** [comment] 2022-05-10 06:32
I have made the necessary changes to the theme, and now it uses a dark theme across the board. So, closing this.
Thanx for the collaboration.

**Closed as completed by Vagelis-Prokopiou** 2022-05-10 06:32 UTC

**Comment by Jeklah** [comment] 2022-05-11 18:29
No problem, glad to have helped!
